Message.create(message: 'Bonjour !! J\'espère que tout va bien !!')
Message.create(message: '¡¡Buenos días!! ¡Espero que todo vaya bien!!')
Message.create(message: 'Buongiorno!! Spero che tu stia bene!!')
Message.create(message: 'Goedemorgen!! Ik hoop dat het goed met je gaat!!')
Message.create(message: 'Bom dia!! Espero que esteja indo tudo bem!!')
Message.create(message: 'おはようございます！！ ごきげんよう！！')
Message.create(message: 'صباح الخير !! آمل أن تكون بخير !!')
Message.create(message: 'Добро утро !! Надам се да вам је добро !!')
Message.create(message: 'God morgon !! Jag hoppas att det går bra med dig !!')
Message.create(message: 'Aloha !! Manalo i ka pono iaʻoe !!')
Message.create(message: 'Hyvää huomenta !! Toivottavasti kaikki menee hyvin !!')
Message.create(message: 'God morgen !! Jeg håber, at det går godt med dig !!')
Message.create(message: 'Guten Morgen !! Ich hoffe, es geht dir gut !!')
Message.create(message: 'Добро јутро !! Надам се да ти је добро !!')
Message.create(message: 'Dzień dobry !! Mam nadzieję, że wszystko idzie dobrze !!')
Message.create(message: 'God morgen !! Jeg håper alt går bra med deg !!')
Message.create(message: 'Καλημέρα !! Ελπίζω να είσαι καλά !!')
Message.create(message: '안녕하세요 !! 잘 지내길 바랍니다 !!')
Message.create(message: 'בוקר טוב !! מקווה שאתה בסדר !!')
Message.create(message: 'Günaydın !! Umarım her şey yolundadır !!')
